dataset:
  root: DB/LibriSpeech
  train_part: 0.95
  name: librispeech
  normalize: touniform
bpe:
  train: true
  model_path: yttm.bpe
train:
  seed: 42
  num_workers: 8
  batch_size: 48
  clip_grad_norm: 15
  epochs: 300
  optimizer:
    lr: 0.01 # 0.0003 - Karpathy great constant for Adam
    weight_decay: 0.0001 # leave default

wandb:
  project: quartznet_librispeech
  log_interval: 20
model:
  name: _quartznet5x5_config
  vocab_size: 80
  feat_in: 64
  # init_mode: kaiming_normal
